
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      ignores:
      - Khaled
      - Nafee
      - Sherif
      - Adel
      - Mahmoud
      - ElDakroury
      - Karim
      - Github
      - NPM
      - EQSP
      - Innopolis
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8