name: README Spell Check

on: [push]

jobs:
  Spell-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Aspell
        run: sudo apt-get update && sudo apt-get install -y aspell aspell-en
      - name: Spell Check
        run: aspell check -mode=markdown -lang=en README.md